# version: "3.6"

services:
  license:
    build:
      context: ./license
      dockerfile: ./Dockerfile
    #image: totvsengpro/license-dev:3.6.1
    container_name: protheus_license_${RELEASE}
    environment:
      - TZ=${TIME_ZONE}
    ports:
      - "5555:5555"
  database:
    build:
      context: ./mssql
      dockerfile: ./Dockerfile
    container_name: protheus_mssql_${RELEASE}
    environment:
      - MSSQL_SA_PASSWORD=${DB_PASS}
      - MSSQL_DB=${DB_NAME}
      - ACCEPT_EULA=Y
      - TZ=${TIME_ZONE}
    user: root
    ports:
      - ${DB_PORT}:1433
    volumes:
      - mssql-data:/var/opt/mssql/data
      - mssql-log:/var/opt/mssql/log
      - mssql-secrets:/var/opt/mssql/secrets
  dbaccess:
    build:
      context: ./dbaccess
      dockerfile: ./Dockerfile
    container_name: protheus_dbaccess_${RELEASE}
    ports:
      - "${DBACCESS_PORT}:7890"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_TYPE=${DB_TYPE}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}_${RELEASE}
      - DB_PORT=${DB_PORT}
      - LICENSE_SERVER=${LICENSE_SERVER}_${RELEASE}
      - TZ=${TIME_ZONE}
    depends_on:
      - database
      - license
  appserver:
    build:
      context: ./appserver
      dockerfile: ./Dockerfile
      #args:
      #  - PROTHEUS_INI=${PROTHEUS_INI_MAIN}

    container_name: protheus_appserver_${RELEASE}
    volumes:
      - "${PROTHEUS_PATH}/protheus_data/:/opt/totvs/protheus/protheus_data/"
      - "${PROTHEUS_PATH}/apo/:/opt/totvs/protheus/apo/"
      - "${PROTHEUS_INI_MAIN}/appserver.ini:/opt/totvs/appserver/appserver.ini"
    ports:
      - "9999:9999"
      - "8080:8080"
    environment:
      - LICENSE_SERVER=${LICENSE_SERVER}_${RELEASE}
      - DBACCESS_SERVER=${DBACCESS_SERVER}_${RELEASE}
      - DBACCESS_ALIAS=${DBACCESS_ALIAS}
      - DBACCESS_PORT=${DBACCESS_PORT}
      - TZ=${TIME_ZONE}
    depends_on:
      - dbaccess
  appserver-rest:
    build:
      context: ./appserver
      dockerfile: ./Dockerfile
      #args:
      #  - PROTHEUS_INI=${PROTHEUS_INI_REST}
    container_name: protheus_rest_${RELEASE}
    volumes:
      - "${PROTHEUS_PATH}/protheus_data/:/opt/totvs/protheus/protheus_data/"
      - "${PROTHEUS_PATH}/apo/:/opt/totvs/protheus/apo/"
      - "${PROTHEUS_INI_REST}/appserver.ini:/opt/totvs/appserver/appserver.ini"
    ports:
      - "9998:9998"
      - "3000:3000"
    environment:
      - LICENSE_SERVER=${LICENSE_SERVER}_${RELEASE}
      - DBACCESS_SERVER=${DBACCESS_SERVER}_${RELEASE}
      - DBACCESS_ALIAS=${DBACCESS_ALIAS}
      - DBACCESS_PORT=${DBACCESS_PORT}
      - TZ=${TIME_ZONE}
    depends_on:
      - dbaccess
  smartview:
    build:
      context: ./smartview
      dockerfile: ./Dockerfile
    container_name: protheus_smartview_${RELEASE}
    environment:
      - SMARTVIEW_PORT=${SMARTVIEW_PORT}
    ports:
      - "${SMARTVIEW_PORT}:${SMARTVIEW_PORT}"
      - "${SMARTVIEW_PORT_ADMIN}:${SMARTVIEW_PORT_ADMIN}"
    depends_on:
      - dbaccess
volumes:
  mssql-data:
  mssql-log:
  mssql-secrets: