[dev]
SourcePath=/opt/totvs/protheus/apo
RootPath=/opt/totvs/protheus/protheus_data/
RPOCustom=/opt/totvs/protheus/apo/custom.rpo
StartPath=/system/ 
RpoDb=top
RpoLanguage=portuguese
RpoVersion=120
Trace=0
DbDataBase=MSSQL
DbServer={{DBACCESS_SERVER}}
DbALIAS={{DBACCESS_ALIAS}}
DbPort={{DBACCESS_PORT}}
TOPMEMOMEGA=1
FWTRACELOG=1
StartSysInDB=1

[drivers]
active=tcp
MULTIPROTOCOLPORT=0
MULTIPROTOCOLPORTSECURE=0

[tcp]
type=tcpip
port=9996

[TopConnect]
Database=MSSQL
Alias={{DBACCESS_ALIAS}}

[General]
;CanAcceptFSRemote=1
InstallPath=/totvs12/protheus/bin/appserver
CONSOLELOG=1
ConsoleFile=console.log
MaxStringSize=500
BuildKillUsers=1
app_environment=dev
MAXSTRINGSIZE=10
GuestKillUser=1

[LOCKSERVER]
Enable=0
Server=NOCONFIG

[LICENSECLIENT]
Server={{LICENSE_SERVER}}
PORT=5555
LOGMESSAGES=0

[MAIL]
Protocol=SMTP
extendSMTP=1
authLogin=1
authNTLM=1
TLSVERSION=1
SSLVERSION=3
TRYPROTOCOLS=0

[SchedulerWF]
Main=WFONSTART
Environment=dev
nParms=4
parm1=99
parm2=01
parm3=dev
parm4=T

[HTTP] 
ENABLE=1 
PATH=/opt/totvs/protheus/protheus_data/\http-root 
PORT=8091
ENVIRONMENT=dev
INSTANCES=1,10 
XFRAMEOPTIONS=ALLOW-FROM * 
UPLOADPATH=\web 

[http://localhost:8091/ws] 
ENABLE=1 
PATH=/opt/totvs/protheus/protheus_data/\web\ws 
ENVIRONMENT= dev
INSTANCENAME=WS 
RESPONSEJOB=JOB_WS_T1 
DEFAULTPAGE=wsindex.apw 

[JOB_WS_T1] 
TYPE=WEBEX 
ENVIRONMENT=dev
INSTANCES=1,10 
SIGAWEB=WS 
INSTANCENAME=WS 
ONSTART=__WSSTART 
ONCONNECT=__WSCONNECT 
PREPAREIN=ALL 

[http://localhost:8091/wf] 
enable=1 
port=8091
PATH=/opt/totvs/protheus/protheus_data/\workflow
environment=dev
responsejob=WF_INDEX 
DEFAULTPAGE=wsindex.apw 

[WF_INDEX]  
TYPE=WEB 
environment= dev
INSTANCES=1,10 
SIGAWEB=WF 
INSTANCENAME=WF 
ONSTART=STARTWEBEX 
ONCONNECT=CONNECTWEBEX 
ONEXIT=FINISHWEBEX 

[MAIL] 
Protocol=SMTP 
ExtendSMTP=1 
SSLVersion=3 
AuthLOGIN=1 
AuthPLAIN=1 
TLSVersion=3 

[OnStart] 
jobs=JOB_WS_T1,WF_INDEX,SchedulerWF
